# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae15c6c1338a5575de1338c43ab8c87629de395e153c964871a25ca346142636c57e5cb4f94df14ba9a225eee8343b146e686b4a4880726e17dcdbc0c8bb7c9f

test:
  secret_key_base: fd52a193fc4f98699e260f7ba00989b2b22c3b7876d1a0bda6a756b5dcbe573f298e7c08ab4c57a81a7eb3bad3bdb91760ed55a3ece372b6ac6feb0b59d662c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
